In [3]:
import numpy as np
import sympy as smp
from sympy import symbols, Eq, solve
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from tabulate import tabulate
import matplotlib

from uncertainties import ufloat
from uncertainties.umath import *
from uncertainties import unumpy
from uncertainties.unumpy import uarray
import uncertainties as unc

In [244]:
matplotlib.use("pgf")
matplotlib.rcParams.update({
    "pgf.texsystem": "pdflatex",
    'font.family': 'serif',
    'text.usetex': True,
    'pgf.rcfonts': False,
})

In [129]:
def Tab(*args):
    
    n = len(args[0])
    
    for i in range(n):
        
        for col in args[0:-1]:
            print("${:.1uL}$ &".format(col[i]), end='')
        
        print(r"${:.1uL}$ \\".format(args[-1][i]))
            
            
            
        #print(("fsrfsrvr {} {} {}").format(col[i] for col in args))
        #print([col[i] for col in args])

# Ukol 1

## Metoda primo

-Obraz d = 95

In [219]:

p = 95 ## predmet
m = np.array([0,5,10,15,20]) ###matnice
c = np.array([69.6,69,67.75,65.9,62.1]) ####cocka

f = 1/(p - c) + 1/(c-m)
1/f

array([18.60884211, 18.48888889, 18.51397059, 18.514875  , 18.46786667])

In [138]:
pu = ufloat(95,0.2)
mu = unumpy.uarray(m, 0.2)
cu = unumpy.uarray(c, 0.2)

f = 10/(1/(pu - cu) + 1/(cu-mu))
print(f)

[186.0884210526316+/-1.4278369063497782
 184.88888888888889+/-1.3280781668002581
 185.13970588235296+/-1.1872527595053743
 185.14874999999995+/-1.0112125124483138
 184.67866666666666+/-0.7781021690974604]


In [139]:
print('{:.1uL}'.format(np.mean(f)))

185.2 \pm 0.9


In [140]:
for i in range(5):
    print(r"{:.1uL} & {:.1uL} & {:.1uL} \\".format(mu[i],cu[i],f[i]))

0.0 \pm 0.2 & 69.6 \pm 0.2 & 186 \pm 1 \\
5.0 \pm 0.2 & 69.0 \pm 0.2 & 185 \pm 1 \\
10.0 \pm 0.2 & 67.8 \pm 0.2 & 185 \pm 1 \\
15.0 \pm 0.2 & 65.9 \pm 0.2 & 185 \pm 1 \\
20.0 \pm 0.2 & 62.1 \pm 0.2 & 184.7 \pm 0.8 \\


In [141]:
Tab(mu,cu,f)

$0.0 \pm 0.2$ &$69.6 \pm 0.2$ &$186 \pm 1$ \\
$5.0 \pm 0.2$ &$69.0 \pm 0.2$ &$185 \pm 1$ \\
$10.0 \pm 0.2$ &$67.8 \pm 0.2$ &$185 \pm 1$ \\
$15.0 \pm 0.2$ &$65.9 \pm 0.2$ &$185 \pm 1$ \\
$20.0 \pm 0.2$ &$62.1 \pm 0.2$ &$184.7 \pm 0.8$ \\


#### Graficky

In [196]:
for x,y in zip((p - c),(c-m)):
    print(x+y)

95.0
90.0
85.0
80.0
75.0


In [245]:
x_range = np.linspace(270,850,100)

plt.figure(figsize = (8,5))

farba = ['royalblue', 'b', 'mediumblue', 'navy', 'indigo']
num = [1,2,3,4,5]

for x,y,clr,i in zip((p - c),(c-m),farba,num):
    plt.plot([x,0],[0,y], lw = .7, color = clr, label = 'Měření {}'.format(i))


plt.plot([0,35],[0,35], color = "k", linestyle = "dashed", lw = 0.8, label = "Identita")

plt.legend(loc='upper right', fontsize=10)



plt.yticks(np.arange(0,70,2), minor = True)
plt.xticks(np.arange(0,35,1), minor = True)

plt.ylim(0,70)
plt.xlim(0,35)

plt.ylabel(r"$a^\prime$ " + r"[cm]", fontsize=12)
plt.xlabel(r"$a$ " + "[cm]", fontsize=12)

plt.savefig('Cocka.pdf', bbox_inches = 'tight')
plt.show()

C:\Users\stepa\AppData\Local\Temp/ipykernel_20924/3351814587.py:28: UserWarning: Matplotlib is currently using pgf, which is a non-GUI backend, so cannot show the figure.
  plt.show()


## Bessel

In [132]:
m = np.array([5,10,15])
p = np.array([95,95,95])

c1 = np.array([30.5,37,43.55])
c2 = np.array([68.9,67.7,65.9])

f = ((p-m)**2-(c2-c1)**2)/(4*(p-m))
f

array([18.404     , 18.47797059, 18.43899219])

In [133]:
pu = ufloat(95,0.2)
mu = unumpy.uarray(m, 0.2)

c1u = unumpy.uarray(c1, 0.2)
c2u = unumpy.uarray(c2, 0.2)

f = 10*((pu-mu)**2-(c2u-c1u)**2)/(4*(pu-mu))
print(f)

[184.04+/-1.0308750764325796 184.77970588235297+/-0.9486062021977815
 184.389921875+/-0.858601830660381]


In [134]:
print('{:.1uL}'.format(np.mean(f)))

184.4 \pm 0.7


In [135]:
for i in range(3):
    print((r"{:.1uL} & {:.1uL} & {:.1uL} & {:.1uL} \\").format(mu[i],c1u[i],c2u[i],f[i]))

5.0 \pm 0.2 & 30.5 \pm 0.2 & 68.9 \pm 0.2 & 184 \pm 1 \\
10.0 \pm 0.2 & 37.0 \pm 0.2 & 67.7 \pm 0.2 & 184.8 \pm 0.9 \\
15.0 \pm 0.2 & 43.5 \pm 0.2 & 65.9 \pm 0.2 & 184.4 \pm 0.9 \\


In [136]:
Tab(mu,c1u,c2u,f)

$5.0 \pm 0.2$ &$30.5 \pm 0.2$ &$68.9 \pm 0.2$ &$184 \pm 1$ \\
$10.0 \pm 0.2$ &$37.0 \pm 0.2$ &$67.7 \pm 0.2$ &$184.8 \pm 0.9$ \\
$15.0 \pm 0.2$ &$43.5 \pm 0.2$ &$65.9 \pm 0.2$ &$184.4 \pm 0.9$ \\


# Ukol 2

## Mikroskopickej obj.

In [164]:
k = 90 - 65.35 #### PREDMETOVA ROVINA

m = np.array([38.3,30,40])
p = np.array([90,90,90])

c1 = np.array([55.7,47.45,57.5])
c2 = np.array([78.05,78.15,78])

f = ((p-m-k)**2-(c2-c1)**2)/(4*(p-m-k))
f

array([2.14584104, 2.17208274, 2.19302268])

In [165]:
ku = ufloat(k,0.2)
pu = ufloat(90,0.2)

mu = unumpy.uarray(m, 0.2)

c1u = unumpy.uarray(c1, 0.2)
c2u = unumpy.uarray(c2, 0.2)

f = ((pu-mu-ku)**2-(c2u-c1u)**2)/(4*(pu-mu-ku))*10
print(f)

[21.458410351201493+/-1.8678711712374991
 21.720827439886804+/-1.953562082796876
 21.930226824457574+/-1.8329244050184155]


In [166]:
print('k:  {:.1uL}'.format(ku))
print('p:  {:.1uL}'.format(pu))

k:  24.7 \pm 0.2
p:  90.0 \pm 0.2


In [167]:
print('{:.1uL}'.format(np.mean(f)))

22 \pm 1


In [168]:
Tab(mu,c1u,c2u,f)

$38.3 \pm 0.2$ &$55.7 \pm 0.2$ &$78.0 \pm 0.2$ &$21 \pm 2$ \\
$30.0 \pm 0.2$ &$47.5 \pm 0.2$ &$78.2 \pm 0.2$ &$22 \pm 2$ \\
$40.0 \pm 0.2$ &$57.5 \pm 0.2$ &$78.0 \pm 0.2$ &$22 \pm 2$ \\


## Okular

In [173]:
k = 90 - 65.35 #### 

m = np.array([30,40])
p = np.array([90,90])

c1 = np.array([83.4,83.3])
c2 = np.array([54.8,64.95])

f = ((p-m-k)**2-(c2-c1)**2)/(4*(p-m-k))
f

array([3.05277581, 3.01676529])

In [174]:
ku = ufloat(k,0.2)
pu = ufloat(90,0.2)

mu = unumpy.uarray(m, 0.2)

c1u = unumpy.uarray(c1, 0.2)
c2u = unumpy.uarray(c2, 0.2)

f = ((pu-mu-ku)**2-(c2u-c1u)**2)/(4*(pu-mu-ku))*10
print(f)

[30.527758132956087+/-1.833663558795365
 30.16765285996055+/-1.6702856142771954]


In [175]:
print('{:.1uL}'.format(np.mean(f)))

30 \pm 1


In [176]:
Tab(mu,c1u,c2u,f)

$30.0 \pm 0.2$ &$83.4 \pm 0.2$ &$54.8 \pm 0.2$ &$31 \pm 2$ \\
$40.0 \pm 0.2$ &$83.3 \pm 0.2$ &$65.0 \pm 0.2$ &$30 \pm 2$ \\


In [177]:
print('k:  {:.1uL}'.format(ku))
print('p:  {:.1uL}'.format(pu))

k:  24.7 \pm 0.2
p:  90.0 \pm 0.2


# Ukol 3

In [185]:
(3.5*10)/4
#3.5 cm...stupnice externi (cela)
#4 mm stupnice na hranolu ji odpovida

8.75

In [186]:
y1 = ufloat(35,1)
y2 = ufloat(4,0.5)

In [187]:
Z = y1/y2
print('{:.1uL}'.format(Z))

9 \pm 1


### Teoreticky

In [188]:
f = ufloat(30,1)
l = 250

In [189]:
Z = l/f
print('{:.1uL}'.format(Z))

8.3 \pm 0.3


# Ukol 4

In [ ]:
## okular - 0
## mikro obj, - 1.9 cm

# Ukol 5

In [105]:
# 1 mm odpovida 3cm
print('zvetseni: ', 30/1)

zvetseni:  30.0


In [111]:
y1 = ufloat(30,1)
y2 = ufloat(1,0.3)

print('y1: ({:.1uL})'.format(y1))
print('y2: ({:.1uL})'.format(y2))

y1: (30 \pm 1)
y2: (1.0 \pm 0.3)


In [112]:
Z = y1/y2
print('Z: ({:.1uL})'.format(Z))

Z: (30 \pm 9)


In [108]:
#### okular: 70cm
#### mikr. objektiv: 75.65cm

In [114]:
f1 = ufloat(2.2,0.1)
f2 = ufloat(3,0.1)
l = 25
delta = ufloat(75.65,0.2) - ufloat(70,0.2)

print('Delta: ({:.1uL})'.format(delta))

Delta: (5.7 \pm 0.3)


In [113]:
Z = (delta*l)/(f1*f2)
print('Z: ({:.1uL})'.format(Z))

Z: (21 \pm 2)


# Ukol 6

In [115]:
#### 3 cm odpovidaji 20 cm
20/3

6.666666666666667

In [116]:
y1 = ufloat(20,1)
y2 = ufloat(3,0.5)

In [117]:
print('y1: ({:.1uL})'.format(y1))
print('y2: ({:.1uL})'.format(y2))

y1: (20 \pm 1)
y2: (3.0 \pm 0.5)


In [118]:
Z = y1/y2
print('Z: ({:.1uL})'.format(Z))

Z: (7 \pm 1)


In [119]:
f1 = ufloat(18.5,0.1)
f2 = ufloat(3,0.1)

In [120]:
Z = f1/f2
print('Z: ({:.1uL})'.format(Z))

Z: (6.2 \pm 0.2)
