In [1]:
import numpy as np
import sympy as smp
from sympy import symbols, Eq, solve
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from tabulate import tabulate
import matplotlib
from uncertainties import ufloat
from uncertainties.umath import *
from uncertainties import unumpy

In [2]:
def mean(arr):
    return np.mean(arr)

def error(x):
    return x.std() / np.sqrt(x.size)

def weighted_error(x, err):
    
    x = np.asarray(x)
    err = np.asarray(err)
    
    average = np.sum(x/(err**2))/np.sum(1/err**2)
    
    average_error = 1/np.sqrt(np.sum(1/err**2))
    
    return average, average_error

def decimal(x):
    return x.replace(',', '.').encode()

def sum_err(x,sx):
    return np.sum(x),np.sqrt(np.sum([np.sum(i**2) for i in sx])) 

def diff_err(x,sx):
    return x[0]-x[1],np.sqrt(np.sum([np.sum(i**2) for i in sx])) 

def times_err(x,sx):
    return np.prod(x), np.prod(x)*np.sqrt(np.sum([np.sum((i/j)**2) for i,j in zip(sx,x)]))

#def frac_err(x,sx):
#    return x[0]/x[1], x[0]/x[1]*np.sqrt(np.sum((sx/x)**2))

def frac_err(x,sx):
    return x[0]/x[1], x[0]/x[1]*np.sqrt(np.sum([np.sum((i/j)**2) for i,j in zip(sx,x)]))
    #return [np.sum((i/j)**2) for i,j in zip(sx,x)]

In [3]:
lamb = 633/10**9

# Ukol 1

## Bez chyb

In [28]:
##### Nejmensi 
k1 = np.array([3,1.2,0.6])/10**2  #### pm 0.1 [1.75,0.6,0.05] 
k2 = np.array([3.25,1.5,0.7])/10**2  #### [3.25,1.5,0.6]
k3 = np.array([3.5,1.7, 0.9])/10**2 ##### [4.8,2.15, 1.1]
k32 = np.array([0.5,0.85,1.2])/10**2
### atrwdni dalsi - 2.7,3.5
#### velky dalsi - 
r = np.array([])

l = (35.5*16 + 469.3)/10**2  ### 165.4+420.5+469.3      ,,,35.5x16 +
l = (165.4+420.5+469.3)/10**2

In [29]:
k1 = np.array([1.75,0.6,0.4] )/10**2  #### pm 0.1 [1.75,0.6,0.05] 
k2 = np.array([3.25,1.5,0.6])/10**2  #### [3.25,1.5,0.6]
k3 = np.array([4.8,2.15, 1.1])/10**2 ##### [4.8,2.15, 1.1]

In [30]:
R1 = 1000*(lamb*1.219*np.sqrt(l**2 + k1**2))/k1
R2 = 1000*(lamb*2.233*np.sqrt(l**2 + k2**2))/k2
R3 = 1000*(lamb*3.238*np.sqrt(l**2 + k3**2))/k3

In [31]:
R = np.array([R1,R2,R3])
print(R.T)

[[0.45737704 0.45114441 0.44294351]
 [1.3340147  0.97747578 0.98888868]
 [2.00102187 2.44368731 1.93282481]]


In [32]:
for r in R.T:
    print('{} +- {}'.format(mean(r), error(r)))

0.45048832218534846 +- 0.0034125438037923
1.1001263876822494 +- 0.09552238960571721
2.1258446611990958 +- 0.13075054357899293


## S chybama

In [70]:
from uncertainties import ufloat
from uncertainties.umath import *
from uncertainties import unumpy

In [57]:
k1u = np.array([ufloat(1.75,0.2),ufloat(0.6,0.2),ufloat(0.4,0.2)])/100
k2u = np.array([ufloat(3.25,0.2),ufloat(1.5,0.2),ufloat(0.6,0.2)])/100
k3u = np.array([ufloat(4.8,0.2),ufloat(2.15,0.2),ufloat(1.1,0.2)])/100

lu = ufloat(1040,20)/100

In [58]:
R1 = 1000*(lamb*1.219*(lu**2 + k1u**2)**(0.5))/k1u
R2 = 1000*(lamb*2.233*(lu**2 + k2u**2)**(0.5))/k2u
R3 = 1000*(lamb*3.238*(lu**2 + k3u**2)**(0.5))/k3u

In [59]:
R = np.array([R1,R2,R3])
print(R.T)

[[0.45856755206209204+/-0.05314434091963415
  0.4523186885711706+/-0.029162187826701973
  0.4440964299455803+/-0.02037935184132384]
 [1.3374870225846933+/-0.4465701917026089
  0.9800200593424988+/-0.1320211963307854
  0.9914626581653606+/-0.09417888855005314]
 [2.0062303483898023+/-1.0038567006020347
  2.4500480077371773+/-0.8180403921836962
  1.937855774860422+/-0.35430235816089434]]


In [61]:
for r in R.T:
    print('{}'.format(mean(r)))

0.452+/-0.022
1.10+/-0.16
2.1+/-0.4


# Ukol 2

## Bez chyb

In [177]:
m = np.array([250,350,400,450,500,550,600,650,750,850]) #### +100 = 20, +50 = 10, 250 = 0, otacka = 250

k1 = np.array([2,1.1,1,0.9,0.8,0.7,0.6,0.5,0.4,0.3])  #### pm 0.1
k2 = np.array([3,2,2,1.8,1.7,1.6,1.4,1.4,1.3,1.1])
k3 = np.array([6,3,3,2.7,2.6,2.3,2.2,2.1,2,1.9])

l = 160.9 + 422.4 + 472.6

In [178]:
D1 = 1000*(lamb*1*np.sqrt(l**2 + k1**2))/k1
D2 = 1000*(lamb*2*np.sqrt(l**2 + k2**2))/k2
D3 = 1000*(lamb*3*np.sqrt(l**2 + k3**2))/k3

In [179]:
D = np.array([D1,D2,D3])
print(D.T)

[[0.33419295 0.4455916  0.33419775]
 [0.60762278 0.6683859  0.6683874 ]
 [0.668385   0.6683859  0.6683874 ]
 [0.74264994 0.74265075 0.74265209]
 [0.83548111 0.78633596 0.77121545]
 [0.9548355  0.83548183 0.8718082 ]
 [1.11397468 0.95483612 0.91143566]
 [1.33676955 0.95483612 0.95483717]
 [1.67096187 1.02828493 1.00257885]
 [2.22794909 1.21524557 1.05534597]]


In [183]:
i = 0
for d in D.T:  ###### SROUB PODKLUYZUJEE
    print('M: {}, F: {} +- {}'.format(m[i], mean(d).round(2), error(d).round(2)))
    i+=1

M: 250, F: 0.37 +- 0.03
M: 350, F: 0.65 +- 0.02
M: 400, F: 0.67 +- 0.0
M: 450, F: 0.74 +- 0.0
M: 500, F: 0.8 +- 0.02
M: 550, F: 0.89 +- 0.03
M: 600, F: 0.99 +- 0.05
M: 650, F: 1.08 +- 0.1
M: 750, F: 1.23 +- 0.18
M: 850, F: 1.5 +- 0.3


## S chybama

In [202]:
m = np.array([250,350,400,450,500,550,600,650,750,850]) #### +100 = 20, +50 = 10, 250 = 0, otacka = 250

k1 = np.array([2,1.1,1,0.9,0.8,0.7,0.6,0.5,0.4,0.3])  #### pm 0.1
k2 = np.array([3,2,2,1.8,1.7,1.6,1.4,1.4,1.3,1.1])
k3 = np.array([6,3,3,2.7,2.6,2.3,2.2,2.1,2,1.9])

l = 160.9 + 422.4 + 472.6

In [203]:
k1u = unumpy.uarray(k1, 0.2)
k2u = unumpy.uarray(k2, 0.2)
k3u = unumpy.uarray(k3, 0.2)
lu = ufloat(l,20)

lu

1055.9+/-20.0

In [204]:
D1 = 1000*(lamb*1*(lu**2 + k1u**2)**0.5)/k1u
D2 = 1000*(lamb*2*(lu**2 + k2u**2)**0.5)/k2u
D3 = 1000*(lamb*3*(lu**2 + k3u**2)**0.5)/k3u

In [205]:
D = np.array([D1,D2,D3])
#print(D.T)

In [206]:
i = 0
for d in D.T:  ###### SROUB PODKLUYZUJEE
    print('${}$ & ${:L}$ \\\\'.format(m[i]/1000, mean(d)))
    i+=1

$0.25$ & $0.371 \pm 0.017$ \\
$0.35$ & $0.65 \pm 0.05$ \\
$0.4$ & $0.67 \pm 0.05$ \\
$0.45$ & $0.74 \pm 0.07$ \\
$0.5$ & $0.80 \pm 0.08$ \\
$0.55$ & $0.89 \pm 0.10$ \\
$0.6$ & $0.99 \pm 0.14$ \\
$0.65$ & $1.08 \pm 0.19$ \\
$0.75$ & $1.23 \pm 0.29$ \\
$0.85$ & $1.5 \pm 0.5$ \\


# Ukol 3 

## Bez chyb

In [202]:
k1 = np.array([35.2,16.1,8.5])/100
k2 = np.array([77.6,52,25.2])/100  ### pm 1

k = np.array([k1,k2])

l1 = 71/100
l2 = 39/100
l3 = 21/100

l = np.array([l1,l2,l3])

In [203]:
### 600/mm

In [204]:
d1 = 1000*(lamb*1*np.sqrt(l**2 + k1**2))/k1
d2 = 1000*(lamb*2*np.sqrt(l**2 + k2**2))/k2

d = np.array([1/d1,1/d2])
d

array([[701.71013384, 602.81846654, 592.7215762 ],
       [582.76876986, 631.91153239, 606.8098575 ]])

In [205]:
d.T

array([[701.71013384, 582.76876986],
       [602.81846654, 631.91153239],
       [592.7215762 , 606.8098575 ]])

In [207]:
i = 0
for N in d.T:  ###### SROUB PODKLUYZUJEE
    print('L{}:, F: {} +- {}'.format(i, mean(N), error(N)))
    i+=1

L0:, F: 642.2394518503643 +- 42.052122513975895
L1:, F: 617.364999461081 +- 10.285952073585985
L2:, F: 599.7657168498192 +- 4.980959622701631


## S chybama

In [208]:
k1 = np.array([35.2,16.1,8.5])/100
k2 = np.array([77.6,52,25.2])/100  ### pm 1

l1 = 71/100
l2 = 39/100
l3 = 21/100

l = np.array([l1,l2,l3])
k = np.array([k1,k2])

In [209]:
ku = unumpy.uarray(k,[0.01,0.01,0.01])
lu = unumpy.uarray(l,[0.1,0.02,0.01])

In [210]:
d1 = 1000*(lamb*1*(lu**2 + ku[0]**2)**0.5)/k1
d2 = 1000*(lamb*2*(lu**2 + ku[1]**2)**0.5)/k2

d = np.array([1/d1,1/d2])

In [218]:
i = 0
for N in d.T:  ###### SROUB PODKLUYZUJEE
    print('L{}:, F: {:L}'.format(i+1, mean(N)))
    i+=1

L1:, F: \left(6.4 \pm 0.6\right) \times 10^{2}
L2:, F: 617 \pm 20
L3:, F: 600 \pm 20


In [213]:
mean(d)

619.7900560537549+/-21.602753366705354

In [219]:
print("{}".format(d.T))

[[701.710133836204+/-79.43040264283667
  582.7687698645246+/-37.62441050495002]
 [602.8184665366961+/-26.96931130556759
  631.911532385466+/-14.020858040448125]
 [592.7215761977618+/-26.16292267548204
  606.8098575018766+/-18.49858115882512]]


In [223]:
for i in lu:
    print("${:L}$ &".format(i), end="")

$0.71 \pm 0.10$ &$0.390 \pm 0.020$ &$0.210 \pm 0.010$ &

# Ukol 4

In [225]:
n = np.array([8,7,3,6,6,6,10])
dx = np.array([10,10,5,11,12,10,15])*200

In [226]:
lamb = 2*dx/n
lamb

array([500.        , 571.42857143, 666.66666667, 733.33333333,
       800.        , 666.66666667, 600.        ])

In [228]:
mean(lamb), error(lamb)

(648.2993197278912, 35.32739677847298)

In [229]:
tab = np.array([n,dx,lamb]).round(1).T

print(tabulate(tab, tablefmt="latex_booktabs"))

\begin{tabular}{rrr}
\toprule
  8 & 2000 & 500   \\
  7 & 2000 & 571.4 \\
  3 & 1000 & 666.7 \\
  6 & 2200 & 733.3 \\
  6 & 2400 & 800   \\
  6 & 2000 & 666.7 \\
 10 & 3000 & 600   \\
\bottomrule
\end{tabular}
